version: "3.3"

services:
  vnc:
    image: "mattia2700/robot-control:vnc"
    ports:
    - "6080:6080"
    volumes:
    - "/Users/francesco/Drive (francesco.meneghin.fm@gmail.com)/UNI/Magistrale/Robot Control/configs:/home/user/Desktop"
